spring: # Spring Configuration
    datasource: # Connection with a database
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            schema: user

    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        database: postgresql

logging:
    level:
        web: trace
        org:
            hibernate: debug
            springframework:
                web: trace

jwt:
    secret_key: 0a07c69f2688f2dd628dd606378c848bed9dd8472f157604f36e18a0f84ef787
    expiration_time: 86400000

server:
    servlet:
        context-path: ${APP_PATH:/mall}
    port: 8099

allowed-origins:
    http://localhost:3000/,
    http://localhost:5173/,